### PR TITLE
Add GoodJob to benchmarks

### PR DESCRIPTION
**Pull request by bensheldon**
Updates other gems too.

Here are the results from running locally on my laptop. 

```bash
$ DATABASE_URL="postgres://localhost:5432/queue_shootout" REDIS_URL=redis://localhost:6379  JOB_COUNT=1000 bundle exec rake
/Users/bensheldon/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/redis-3.0.7/lib/redis/client.rb:386: warning: constant ::Fixnum is deprecated
Benchmarking delayed_job, good_job, queue_classic, que
  QUIET = false
  ITERATIONS = 5
  DATABASE_URL = postgres://localhost:5432/queue_shootout
  JOB_COUNT = 1000
  TEST_PERIOD = 0.2
  WARMUP_PERIOD = 0.2
  SYNCHRONOUS_COMMIT = on

Iteration #1:
delayed_job: 1 => 129.8, 2 => 311.5, 3 => 408.5, 4 => 474.4, 5 => 554.4, 6 => 613.7, 7 => 503.7, 8 => 424.3, 9 => 325.1, 10 => 239.5, 11 => 149.3
delayed_job: Peaked at 6 workers with 613.7 jobs/second
good_job: 1 => 154.6, 2 => 299.6, 3 => 447.9, 4 => 469.0, 5 => 344.2, 6 => 184.5, 7 => 87.7, 8 => 0.0, 9 => 0.0
good_job: Peaked at 4 workers with 469.0 jobs/second
queue_classic: 1 => 234.2, 2 => 589.2, 3 => 948.2, 4 => 1137.4, 5 => 1285.3, 6 => 1233.1, 7 => 1293.0, 8 => 1287.2, 9 => 1267.7, 10 => 1201.5, 11 => 1191.6, 12 => 1158.6
queue_classic: Peaked at 7 workers with 1293.0 jobs/second
que: 1 => 302.2, 2 => 684.1, 3 => 951.6, 4 => 1090.7, 5 => 1133.5, 6 => 1102.6, 7 => 1103.8, 8 => 1117.9, 9 => 1087.6, 10 => 1084.0
que: Peaked at 5 workers with 1133.5 jobs/second

Iteration #2:
delayed_job: 1 => 149.6, 2 => 319.6, 3 => 473.8, 4 => 568.6, 5 => 568.8, 6 => 604.3, 7 => 569.6, 8 => 386.0, 9 => 334.5, 10 => 159.4, 11 => 104.5
delayed_job: Peaked at 6 workers with 604.3 jobs/second
good_job: 1 => 164.2, 2 => 316.1, 3 => 448.9, 4 => 468.7, 5 => 359.3, 6 => 214.5, 7 => 92.6, 8 => 0.0, 9 => 0.0
good_job: Peaked at 4 workers with 468.7 jobs/second
queue_classic: 1 => 258.8, 2 => 558.8, 3 => 808.3, 4 => 1023.5, 5 => 1163.5, 6 => 1193.9, 7 => 1173.5, 8 => 1177.5, 9 => 1123.8, 10 => 1113.2, 11 => 1047.6
queue_classic: Peaked at 6 workers with 1193.9 jobs/second
que: 1 => 298.4, 2 => 643.4, 3 => 873.9, 4 => 1058.4, 5 => 853.5, 6 => 1107.0, 7 => 1128.7, 8 => 1097.4, 9 => 1103.7, 10 => 1148.0, 11 => 1133.5, 12 => 1128.6, 13 => 1052.2, 14 => 1042.7, 15 => 976.3
que: Peaked at 10 workers with 1148.0 jobs/second

Iteration #3:
delayed_job: 1 => 159.3, 2 => 303.2, 3 => 478.9, 4 => 469.2, 5 => 309.5, 6 => 544.4, 7 => 485.8, 8 => 419.4, 9 => 324.5, 10 => 243.2, 11 => 139.6
delayed_job: Peaked at 6 workers with 544.4 jobs/second
good_job: 1 => 169.6, 2 => 967.8, 3 => 867.9, 4 => 867.9, 5 => 772.6, 6 => 1180.4, 7 => 923.8, 8 => 1010.8, 9 => 1023.3, 10 => 540.8, 11 => 537.6
good_job: Peaked at 6 workers with 1180.4 jobs/second
queue_classic: 1 => 259.6, 2 => 619.2, 3 => 908.7, 4 => 1095.6, 5 => 1238.2, 6 => 1223.1, 7 => 1285.6, 8 => 1138.1, 9 => 1199.2, 10 => 1219.1, 11 => 1213.1, 12 => 1170.8
queue_classic: Peaked at 7 workers with 1285.6 jobs/second
que: 1 => 325.5, 2 => 638.7, 3 => 948.4, 4 => 1073.8, 5 => 1151.7, 6 => 1128.3, 7 => 863.5, 8 => 1108.7, 9 => 1145.2, 10 => 1103.2
que: Peaked at 5 workers with 1151.7 jobs/second

Iteration #4:
delayed_job: 1 => 119.7, 2 => 279.5, 3 => 444.5, 4 => 518.6, 5 => 540.6, 6 => 509.4, 7 => 428.7, 8 => 409.3, 9 => 283.3, 10 => 203.5
delayed_job: Peaked at 5 workers with 540.6 jobs/second
good_job: 1 => 596.8, 2 => 1133.4, 3 => 1440.7, 4 => 1711.4, 5 => 1653.8, 6 => 1165.7, 7 => 1428.8, 8 => 1306.1, 9 => 1286.1
good_job: Peaked at 4 workers with 1711.4 jobs/second
queue_classic: 1 => 249.3, 2 => 578.0, 3 => 862.6, 4 => 1086.0, 5 => 1155.9, 6 => 1195.6, 7 => 1197.9, 8 => 1153.1, 9 => 1171.9, 10 => 1162.9, 11 => 1117.4, 12 => 1093.4
queue_classic: Peaked at 7 workers with 1197.9 jobs/second
que: 1 => 308.2, 2 => 619.7, 3 => 869.0, 4 => 1074.0, 5 => 1146.9, 6 => 1087.0, 7 => 1107.5, 8 => 1133.8, 9 => 1093.9, 10 => 994.5
que: Peaked at 5 workers with 1146.9 jobs/second

Iteration #5:
delayed_job: 1 => 199.2, 2 => 349.3, 3 => 489.5, 4 => 578.2, 5 => 554.5, 6 => 501.9, 7 => 439.2, 8 => 349.5, 9 => 282.6
delayed_job: Peaked at 4 workers with 578.2 jobs/second
good_job: 1 => 645.1, 2 => 1130.8, 3 => 1482.0, 4 => 1741.1, 5 => 1656.5, 6 => 1462.2, 7 => 1476.2, 8 => 1246.4, 9 => 1211.5
good_job: Peaked at 4 workers with 1741.1 jobs/second
queue_classic: 1 => 280.4, 2 => 644.0, 3 => 953.0, 4 => 1134.0, 5 => 1245.2, 6 => 1303.6, 7 => 1248.8, 8 => 1272.0, 9 => 1228.5, 10 => 1244.0, 11 => 1183.8
queue_classic: Peaked at 6 workers with 1303.6 jobs/second
que: 1 => 344.3, 2 => 616.5, 3 => 893.9, 4 => 1047.3, 5 => 934.2, 6 => 1133.5, 7 => 1108.6, 8 => 1108.7, 9 => 1132.1, 10 => 1055.4, 11 => 1086.7
que: Peaked at 6 workers with 1133.5 jobs/second

delayed_job jobs per second: avg = 576.2, max = 613.7, min = 540.6, stddev = 33.4
good_job jobs per second: avg = 1114.1, max = 1741.1, min = 468.7, stddev = 629.9
queue_classic jobs per second: avg = 1254.8, max = 1303.6, min = 1193.9, stddev = 54.1
que jobs per second: avg = 1142.7, max = 1151.7, min = 1133.5, stddev = 8.6

Total runtime: 100.4 seconds
```

Observations:
- I'm the author of GoodJob and that standard deviation scares me.
- QueueClassic seems to be screaming now.

### CODE REVIEW

**Comment by chanks** [comment]
Hi Ben, I'm happy to merge this since you clearly put some effort into it, but since I don't really spend much time with Ruby open-source anymore, I think I'll also be marking the repo as no longer maintained. I could link to your fork, if you're planning on maintaining it?

(I realize that the "maintenance" required for this repo isn't exactly hefty, I just don't maintain Que anymore and don't really keep up with what's going on in Ruby job queues, or the Rails community in general)

**Comment by bensheldon** [comment]
@chanks thank you! I appreciate the response and I understand. You're welcome to link to my fork to get it off your plate.

@siegy22 Would the `que-rb` organization be a good home for `queue-shootout`? I think of the historical relevance of these benchmarks being closely tied to Que.

**Comment by chanks** [comment]
Merged, and README updated!

**Comment by vtt** [comment]
This shootout benchmark seems to give random results... I've ran with different JOB_COUNT from 10 to 10000; and the results are all over the place; there is no consistent performance trend among the candidates.  Is this a flaw in the benchmark design?

**Comment by bensheldon** [comment]
@vtt the main repository for this project has moved to https://github.com/bensheldon/queue-shootout. 

But to briefly answer your question: I'm not sure. The benchmarks have been very touchy for me based on system resources. I'm curious about what question you're looking to answer. Please do open an Issue on https://github.com/bensheldon/queue-shootout to discuss further.

**Pull request merged**
